::Saxon-B 9.1.0.8

:: parameters:
	SET localOntologyIRIUserDefined="localOntologyIRIUserDefined"
	::relative paths of input XML Schemas (separated by '/' and ending with '/') [default: 'XML Schemas/']:
		SET parameterRelativePathInputXMLSchemas=XMLSchemas/
		SET parameterRelativePathInputXMLSchemasGenericTestCases=XMLSchemas/genericTestCases/
		SET parameterRelativePathInputXMLSchemasDDI31=XMLSchemas/DDI3.1/
		SET parameterRelativePathInputXMLSchemasXHTML=XMLSchemas/DDI3.1/XHTML/

::relative paths of input XML Schemas (ending with '\'):
	SET relativePathInputXMLSchemasGenericTestCases=XMLSchemas\genericTestCases\
	SET relativePathInputXMLSchemasDDI31=XMLSchemas\DDI3.1\
	SET relativePathInputXMLSchemasXHTML=XMLSchemas\DDI3.1\XHTML\

:: relative paths of generated ontologies (ending with '\'):
	SET relativePathGeneratedOntologies=generatedOntologies\
	SET relativePathGeneratedOntologiesGenericTestCases=generatedOntologies\genericTestCases\
	SET relativePathGeneratedOntologiesDDI31=generatedOntologies\DDI3.1\
	SET relativePathGeneratedOntologiesXHTML=generatedOntologies\DDI3.1\XHTML\

ECHO OFF

ECHO %TIME:~0,12%

:: generic test cases:

	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Schema.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Schema.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Include.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Include.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Import.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Import.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Redefine.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Annotation.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Annotation.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Documentation.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Documentation.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%SimpleType.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%SimpleType.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%ComplexType.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%ComplexType.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%ComplexType.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%ComplexType.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Group.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Group.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%AttributeGroup.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%AttributeGroup.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Element.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Element.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Attribute.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Attribute.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Notation.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Notation.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Appinfo.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Appinfo.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Documentation.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Documentation.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Restriction.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Restriction.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%List.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%List.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Union.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Union.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Union.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Union.owl  -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%SimpleContent.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%SimpleContent.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%ComplexContent.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%ComplexContent.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%All.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%All.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Choice.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Choice.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Sequence.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Sequence.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%AnyAttribute.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%AnyAttribute.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Unique.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Unique.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Key.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Key.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Keyref.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Keyref.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Extension.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Extension.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Any.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Any.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Selector.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Selector.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%Field.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%Field.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%genericTestCases.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%genericTestCases.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%testCases.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%testCases.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%LocalOntologyIRI.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%LocalOntologyIRI.owl -warnings:silent localOntologyIRIUserDefined=%localOntologyIRIUserDefined%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%LocalOntologyIRI.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%LocalOntologyIRI.owl -warnings:silent localOntologyIRIUserDefined=%localOntologyIRIUserDefined%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%AssertionalKnowledge.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%AssertionalKnowledge.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%

	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%XML2RDF-noTargetNamespace.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%XML2RDF-noTargetNamespace.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases% localOntologyIRIUserDefined="XML2RDF-noTargetNamespace"
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%XML2RDF-qualifiedLocalElements.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%XML2RDF-qualifiedLocalElements.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%XML2RDF-unqualifiedLocalElements.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%XML2RDF-unqualifiedLocalElements.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%XML2RDF-unqualifiedLocalElements-2.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%XML2RDF-unqualifiedLocalElements-2.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%XML2RDF-unqualifiedLocalElements-3.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%XML2RDF-unqualifiedLocalElements-3.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%XML2RDF-unqualifiedLocalElements-4.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%XML2RDF-unqualifiedLocalElements-4.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%XML2RDF-includeUnqualifiedLocalElements.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%XML2RDF-includeUnqualifiedLocalElements.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%XML2RDF-importUnqualifiedLocalElements.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%XML2RDF-importUnqualifiedLocalElements.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%XML2RDF-sequence.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%XML2RDF-sequence.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%XML2RDF-sequence-qualified.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%XML2RDF-sequence-qualified.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%XML2RDF-sequence-unqualified.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%XML2RDF-sequence-unqualified.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%XML2RDF-all.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%XML2RDF-all.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%XML2RDF-choice.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%XML2RDF-choice.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%unqualified_schema-element-complexType-sequence-element.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%unqualified_schema-element-complexType-sequence-element.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%qualified_schema-element-complexType-sequence-element.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%qualified_schema-element-complexType-sequence-element.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%qualified_all-element.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%qualified_all-element.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%unqualified_all-element.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%unqualified_all-element.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%unqualified_schema-element-complexType-complexContent-extension-sequence.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%unqualified_schema-element-complexType-complexContent-extension-sequence.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%unqualified_schema-element-complexType-complexContent-extension-all.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%unqualified_schema-element-complexType-complexContent-extension-all.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%s_e-e_1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%s_e-e_1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%s_e-e_5.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%s_e-e_5.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%s_e-s_e__e_1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%s_e-s_e__e_1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%s_s-e_minMaxOccurs.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%s_s-e_minMaxOccurs.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%s_s_e__s_e\s_s_e__s_e_9.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%s_s_e__s_e\s_s_e__s_e_9.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%s_s_e__s_e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%e_ct_c\e_ct_c.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%e_ct_c\e_ct_c.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%e_ct_c/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%c_e_minMaxOccurs\c_e_minMaxOccurs.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%c_e_minMaxOccurs\c_e_minMaxOccurs.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%c_e_minMaxOccurs/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%group\group.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%group\group.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%group/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%e_ct_a\e_ct_a.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%e_ct_a\e_ct_a.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%e_ct_a/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%e_ct_s_s_e-s_e__e\e_ct_s_s_e-s_e__e.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%e_ct_s_s_e-s_e__e\e_ct_s_s_e-s_e__e.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%e_ct_s_s_e-s_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%e_ct_s_e-g_s_e____e\e_ct_s_e-g_s_e____e.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%e_ct_s_e-g_s_e____e\e_ct_s_e-g_s_e____e.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%e_ct_s_e-g_s_e____e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%e_ct_s\e_ct_s.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%e_ct_s\e_ct_s.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%e_ct_s/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%e_ct_cc_ex\e_ct_cc_ex.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%e_ct_cc_ex\e_ct_cc_ex.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%e_ct_cc_ex/
	
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%IJMSO.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%IJMSO.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%IJMSO/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%ISWC2012.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%ISWC2012.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%ISWC2012/
	
	
	::element
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%element\element.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%element\element.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%element/	
	
	::complexType
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%complexType\complexType.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%complexType\complexType.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%complexType/	
	
	::sequence
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\sequence.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\sequence.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/
	
	::sequence\s_e_ct_s\e-e
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\e-e\1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\e-e\1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/e-e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\e-e\2.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\e-e\2.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/e-e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\e-e\3.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\e-e\3.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/e-e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\e-e\4.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\e-e\4.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/e-e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\e-e\5.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\e-e\5.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/e-e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\e-e\6.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\e-e\6.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/e-e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\e-e\7.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\e-e\7.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/e-e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\e-e\8.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\e-e\8.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/e-e/
	
	::sequence\s_e_ct_s\s_e__e
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\s_e__e\1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\s_e__e\1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/s_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\s_e__e\2.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\s_e__e\2.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/s_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\s_e__e\3.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\s_e__e\3.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/s_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\s_e__e\4.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\s_e__e\4.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/s_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\s_e__e\5.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\s_e__e\5.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/s_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\s_e__e\6.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\s_e__e\6.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/s_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\s_e__e\7.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\s_e__e\7.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/s_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\s_e__e\8.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\s_e__e\8.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/s_e__e/
	
	::sequence\s_e_ct_s\c_e__e
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\c_e__e\1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\c_e__e\1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/c_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\c_e__e\2.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\c_e__e\2.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/c_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\c_e__e\3.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\c_e__e\3.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/c_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\c_e__e\4.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\c_e__e\4.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/c_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\c_e__e\5.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\c_e__e\5.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/c_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\c_e__e\6.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\c_e__e\6.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/c_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\c_e__e\7.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\c_e__e\7.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/c_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%sequence\s_e_ct_s\c_e__e\8.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%sequence\s_e_ct_s\c_e__e\8.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%sequence/s_e_ct_s/c_e__e/
	
	
	::choice
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%choice\choice.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%choice\choice.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%choice/
	
	::choice\s_e_ct_c\e-e
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%choice\s_e_ct_c\e-e\1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%choice\s_e_ct_c\e-e\1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%choice/s_e_ct_c/e-e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%choice\s_e_ct_c\e-e\2.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%choice\s_e_ct_c\e-e\2.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%choice/s_e_ct_c/e-e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%choice\s_e_ct_c\e-e\3.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%choice\s_e_ct_c\e-e\3.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%choice/s_e_ct_c/e-e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%choice\s_e_ct_c\e-e\4.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%choice\s_e_ct_c\e-e\4.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%choice/s_e_ct_c/e-e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%choice\s_e_ct_c\e-e\5.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%choice\s_e_ct_c\e-e\5.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%choice/s_e_ct_c/e-e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%choice\s_e_ct_c\e-e\6.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%choice\s_e_ct_c\e-e\6.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%choice/s_e_ct_c/e-e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%choice\s_e_ct_c\e-e\7.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%choice\s_e_ct_c\e-e\7.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%choice/s_e_ct_c/e-e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%choice\s_e_ct_c\e-e\8.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%choice\s_e_ct_c\e-e\8.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%choice/s_e_ct_c/e-e/
	
	::choice\s_e_ct_c\c_e-e
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%choice\s_e_ct_c\c_e__e\1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%choice\s_e_ct_c\c_e__e\1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%choice/s_e_ct_c/c_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%choice\s_e_ct_c\c_e__e\2.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%choice\s_e_ct_c\c_e__e\2.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%choice/s_e_ct_c/c_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%choice\s_e_ct_c\c_e__e\3.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%choice\s_e_ct_c\c_e__e\3.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%choice/s_e_ct_c/c_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%choice\s_e_ct_c\c_e__e\4.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%choice\s_e_ct_c\c_e__e\4.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%choice/s_e_ct_c/c_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%choice\s_e_ct_c\c_e__e\5.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%choice\s_e_ct_c\c_e__e\5.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%choice/s_e_ct_c/c_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%choice\s_e_ct_c\c_e__e\6.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%choice\s_e_ct_c\c_e__e\6.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%choice/s_e_ct_c/c_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%choice\s_e_ct_c\c_e__e\7.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%choice\s_e_ct_c\c_e__e\7.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%choice/s_e_ct_c/c_e__e/
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%choice\s_e_ct_c\c_e__e\8.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%choice\s_e_ct_c\c_e__e\8.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%choice/s_e_ct_c/c_e__e/
	
	
	::group
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%group\group.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%group\group.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%group/
	
	
	::use case
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%useCase\useCase.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%useCase\useCase.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%useCase/	
	
	::test
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasGenericTestCases%test\test.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesGenericTestCases%test\test.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasGenericTestCases%test/	
	
	
:: DDI 3.1:

	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%archive.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%archive.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%comparative.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%comparative.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%conceptualcomponent.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%conceptualcomponent.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%datacollection.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%datacollection.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%dataset.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%dataset.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%dcelements.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%dcelements.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%ddiprofile.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%ddiprofile.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%ddi-xhtml11.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%ddi-xhtml11.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%ddi-xhtml11-model-1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%ddi-xhtml11-model-1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%ddi-xhtml11-modules-1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%ddi-xhtml11-modules-1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%group.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%group.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%instance.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%instance.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%logicalproduct.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%logicalproduct.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%physicaldataproduct.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%physicaldataproduct.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%physicaldataproduct_ncube_inline.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%physicaldataproduct_ncube_inline.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%physicaldataproduct_ncube_normal.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%physicaldataproduct_ncube_normal.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%physicaldataproduct_ncube_tabular.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%physicaldataproduct_ncube_tabular.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%physicaldataproduct_proprietary.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%physicaldataproduct_proprietary.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%physicalinstance.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%physicalinstance.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%reusable.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%reusable.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%simpledc20021212.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%simpledc20021212.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%studyunit.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%studyunit.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasDDI31%xml.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesDDI31%xml.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasDDI31%


:: XHTML

	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasXHTML%xhtml-attribs-1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesXHTML%xhtml-attribs-1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasXHTML%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasXHTML%xhtml-bdo-1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesXHTML%xhtml-bdo-1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasXHTML%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasXHTML%xhtml-blkphras-1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesXHTML%xhtml-blkphras-1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasXHTML%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasXHTML%xhtml-blkpres-1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesXHTML%xhtml-blkpres-1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasXHTML%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasXHTML%xhtml-blkstruct-1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesXHTML%xhtml-blkstruct-1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasXHTML%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasXHTML%xhtml-charent-1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesXHTML%xhtml-charent-1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasXHTML%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasXHTML%xhtml-datatypes-1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesXHTML%xhtml-datatypes-1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasXHTML%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasXHTML%xhtml-framework-1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesXHTML%xhtml-framework-1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasXHTML%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasXHTML%xhtml-hypertext-1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesXHTML%xhtml-hypertext-1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasXHTML%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasXHTML%xhtml-inlphras-1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesXHTML%xhtml-inlphras-1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasXHTML%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasXHTML%xhtml-inlpres-1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesXHTML%xhtml-inlpres-1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasXHTML%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasXHTML%xhtml-inlstruct-1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesXHTML%xhtml-inlstruct-1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasXHTML%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasXHTML%xhtml-inlstyle-1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesXHTML%xhtml-inlstyle-1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasXHTML%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasXHTML%xhtml-list-1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesXHTML%xhtml-list-1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasXHTML%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasXHTML%xhtml-notations-1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesXHTML%xhtml-notations-1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasXHTML%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasXHTML%xhtml-pres-1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesXHTML%xhtml-pres-1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasXHTML%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasXHTML%xhtml-table-1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesXHTML%xhtml-table-1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasXHTML%
	::java net.sf.saxon.Transform -s:%relativePathInputXMLSchemasXHTML%xhtml-text-1.xsd -xsl:XSD-2-OWL.xsl -o:%relativePathGeneratedOntologiesXHTML%xhtml-text-1.owl -warnings:silent relativePathInputXMLSchemas=%parameterRelativePathInputXMLSchemasXHTML%

	
:: KML 2.1:
   ::java net.sf.saxon.Transform -s:XMLSchemas\KML2.1\kml21.xsd -xsl:XSD-2-OWL.xsl -o:generatedOntologies\KML2.1\kml21.owl -warnings:silent relativePathInputXMLSchemas=XMLSchemas/KML2.1/

:: Simple DC:
   ::java net.sf.saxon.Transform -s:XMLSchemas\SimpleDC\simpledc20021212.xsd -xsl:XSD-2-OWL.xsl -o:generatedOntologies\SimpleDC\simpledc20021212.owl -warnings:silent relativePathInputXMLSchemas=XMLSchemas/SimpleDC/	
	
:: Qualified DC:
   ::java net.sf.saxon.Transform -s:XMLSchemas\QualifiedDC\dc.xsd -xsl:XSD-2-OWL.xsl -o:generatedOntologies\QualifiedDC\dc.owl -warnings:silent relativePathInputXMLSchemas=XMLSchemas/QualifiedDC/
   ::java net.sf.saxon.Transform -s:XMLSchemas\QualifiedDC\dcmitype.xsd -xsl:XSD-2-OWL.xsl -o:generatedOntologies\QualifiedDC\dcmitype.owl -warnings:silent relativePathInputXMLSchemas=XMLSchemas/QualifiedDC/	
   ::java net.sf.saxon.Transform -s:XMLSchemas\QualifiedDC\dcterms.xsd -xsl:XSD-2-OWL.xsl -o:generatedOntologies\QualifiedDC\dcterms.owl -warnings:silent relativePathInputXMLSchemas=XMLSchemas/QualifiedDC/	
   ::java net.sf.saxon.Transform -s:XMLSchemas\QualifiedDC\qualifieddc.xsd -xsl:XSD-2-OWL.xsl -o:generatedOntologies\QualifiedDC\qualifieddc.owl -warnings:silent relativePathInputXMLSchemas=XMLSchemas/QualifiedDC/	
   ::java net.sf.saxon.Transform -s:XMLSchemas\QualifiedDC\simpledc.xsd -xsl:XSD-2-OWL.xsl -o:generatedOntologies\QualifiedDC\simpledc.owl -warnings:silent relativePathInputXMLSchemas=XMLSchemas/QualifiedDC/	
	
::KML
   ::java net.sf.saxon.Transform -s:XMLSchemas\KML2.1\kml21.xsd -xsl:XSD-2-OWL.xsl -o:generatedOntologies\KML2.1\kml21.owl -warnings:silent relativePathInputXMLSchemas=XMLSchemas/KML2.1/	

::ASF
   java net.sf.saxon.Transform -s:XMLSchemas\ASF\atom.xsd -xsl:XSD-2-OWL.xsl -o:generatedOntologies\ASF\atom.owl -warnings:silent relativePathInputXMLSchemas=XMLSchemas/ASF/	

   
::AIM
::java net.sf.saxon.Transform -s:XMLSchemas\AIM\AIM_v4_rv44_XML.xsd -xsl:XSD-2-OWL.xsl -o:generatedOntologies\AIM\AIM_v4_rv44_XML.owl -warnings:silent relativePathInputXMLSchemas=XMLSchemas/AIM/	
java net.sf.saxon.Transform -s:XMLSchemas\AIM\ISO_datatypes_Narrative.xsd -xsl:XSD-2-OWL.xsl -o:generatedOntologies\AIM\ISO_datatypes_Narrative.owl -warnings:silent relativePathInputXMLSchemas=XMLSchemas/AIM/
	
ECHO %TIME:~0,12%
	
PAUSE transformation successful!