<!-- later this will be generated by the spring application, somewhere else? -->
<div id="nav_main">
	<ul class="homeButton" style="width: 30px">
		<li>
			<a href="<@spring.url '/home' />">
				<img alt="home button" src="<@spring.url '/resources/images/gs_home.png' />" />
			</a>
		</li>
	</ul>
	<ul class="MISSY_nav_main_marginFix">
	
		<!--
		<li<#if link?? & link == 'home'> id="current"</#if>>
			<a href="<@spring.url '/home' />">Home</a>
		</li>
		-->

		<li<#if link?? & link == 'owl2'> id="current"</#if>>
			<a href="<@spring.url '/owl2' />">OWL 2</a>
		</li>
		
		<li<#if link?? & link == 'dsp'> id="current"</#if>>
			<a href="<@spring.url '/dsp' />">DSP</a>
		</li>
		
		<li<#if link?? & link == 'dsp2'> id="current"</#if>>
			<a href="<@spring.url '/dsp2' />">DSP2</a>
		</li>
		
		<li<#if link?? & link == 'rs'> id="current"</#if>>
			<a href="<@spring.url '/rs' />">ReSh</a>
		</li>
		
		<li<#if link?? & link == 'shex'> id="current"</#if>>
			<a href="<@spring.url '/shex' />">ShEx</a>
		</li>
		
		<li<#if link?? & link == 'gclo'> id="current"</#if>>
			<a href="<@spring.url '/gclo' />">RDF-CV</a>
		</li>
		
		<li<#if link?? & link == 'skos'> id="current"</#if>>
			<a href="<@spring.url '/skos' />">SKOS</a>
		</li>
		
		<li<#if link?? & link == 'xkos'> id="current"</#if>>
			<a href="<@spring.url '/xkos' />">XKOS</a>
		</li>
		
		<li<#if link?? & link == 'disco'> id="current"</#if>>
			<a href="<@spring.url '/disco' />">Disco</a>
		</li>
		
		<li<#if link?? & link == 'datacube'> id="current"</#if>>
			<a href="<@spring.url '/datacube' />">Data Cube</a>
		</li>
		
		<li<#if link?? & link == 'phdd'> id="current"</#if>>
			<a href="<@spring.url '/phdd' />">PHDD</a>
		</li>
		
		<li<#if link?? & link == 'dcat'> id="current"</#if>>
			<a href="<@spring.url '/dcat' />">DCAT</a>
		</li>
		
	</ul>
</div>